version: '3.8'
services:
  db:
    image: postgres:alpine3.18
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: fzrsahi
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: task_one_dikti

  dev:
    image: postgres:alpine3.18
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: fzrsahi
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: task_one_dikti_dev